[[redirects]]
  from = "/curriculum-vitae"
  to = "/curriculum-vitae.pdf"
  status = 200

[[redirects]]
  from = "/resume"
  to = "/curriculum-vitae.pdf"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
